DROP TABLE IF EXISTS `gdefinitions`;					
SET @saved_cs_client     = @@character_set_client;					
SET character_set_client = utf8;					
CREATE TABLE `gdefinitions` (					
  `id` int(11) NOT NULL auto_increment,					
  `DefinitionID` varchar(100) NOT NULL,					
  `Description` varchar(1000) NOT NULL,					
  `DataType` varchar(100) ,					
  `Value` varchar(400) ,					
  `Example` varchar(200) ,					
  PRIMARY KEY  (`id`)					
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;					
SET character_set_client = @saved_cs_client;					
LOCK TABLES `gdefinitions` WRITE;					
INSERT INTO `gdefinitions` (`id`, `DefinitionID`, `Description`, `DataType`, `Value`, `Example` ) VALUES 					
(1,	'service',	'Service type identifier.',	'Character String',	'Must be \"GLS\"',	'GLS'),
(2,	'version',	'GLS specification and schema version.',	'Character String',	'Must be \"0.12\"',	'0.12'),
(3,	'xml:lang',	'Language of any human-readable text (e.g. \"en-CA\")',	'Character String',	'Two or five digit RFC 4646 language tag',	'en-CA'),
(4,	'xmlns',	'default XML namespace.',	'URL',	'Must be \"http://www.opengis.net/gls/0.12\".',	'http://www.opengis.net/gls/0.12'),
(5,	'xmlns:ows',	'OWS XML namespace',	'URL',	'Must be \"http://www.opengis.net/ows/1.1\"',	'http://www.opengis.net/ows/1.1'),
(6,	'xmlns:xsi',	'XML Schema namespace',	'URL',	'Must be \"http://www.w3.org/2001/XMLSchema-instance\"',	'http://www.w3.org/2001/XMLSchema-instance'),
(7,	'xsi:schemaLocation',	'location of the GLS Schema',	'URL',	'Must include \"http://www.opengis.net/gls/0.12\".  May include location of copy to be used.',	'http://www.opengis.net/gls/0.12  ../glsDescribeFrameworks_response.xsd'),
(8,	'GDAS',	'Root element containing attribute data and all associated metadata ',	'XML elements',	'',	''),
(9,	'Framework',	'Contains XML elements that describe a spatial framework.',	'XML elements',	'',	''),
(10,	'FrameworkURI',	'A URI that uniquely references the spatial framework.  Normally a URL, but a URN may be used.',	'URI',	'',	''),
(11,	'Organization',	'The name of the organization that is responsible for maintaining the framework dataset. ',	'Character String',	'',	''),
(12,	'Title',	'A human readable sentence fragment that describes the object and may be used to form a title or to populate a picklist. ',	'Character String',	'',	''),
(13,	'Abstract',	'A complete human readable description of the object.',	'Character String',	'',	''),
(14,	'ReleaseDate',	'The date on which this object was first released for use.  ',	'Character String',	'',	''),
(15,	'Documentation',	'The URL of a web-accessible resource containing documentation describing this object.',	'URL',	'',	''),
(16,	'FrameworkKey',	'The key field within the framework dataset (i.e. in the GIS) that is referenced by all datasets that apply to this Framework.',	'Character String',	'',	''),
(17,	'BoundingBox',	'Identifies the bounding box of the spatial framework using the WGS84 CRS.',	'XML elements',	'',	''),
(18,	'Dataset',	'Contains XML elements that describe a dataset.  This dataset contains attribute information that applies to the spatial framework.',	'XML elements',	'',	''),
(19,	'Minimum',	'Contains XML elements that describe the minimum coordinates of the spatial framework.',	'XML elements',	'',	''),
(20,	'Maximum',	'Contains XML elements that describe the maximum coordinates of the spatial framework. ',	'XML elements',	'',	''),
(21,	'Latitude',	'Latitude coordinate in the WGS84 Coordinate Reference System.',	'Decimal',	'',	''),
(22,	'Longitude',	'Longitude coordinate in the WGS84 Coordinate Reference System.',	'Decimal',	'',	''),
(23,	'DatasetURI',	'A URI that uniquely identifies the attribute dataset.  Normally a URL, but a URN may be used.',	'URI',	'',	''),
(24,	'DatasetKey',	'The key field within the attribute dataset (i.e. the corporate database) that references the foreign key found in the spatial framework.  ',	'Character String',	'',	''),
(25,	'KeyRelationship',	'Identifies if the relationship between the Framework and the Attribute datasets are 1:1 or 1:many.  \"one\" indicates that there is at most one record in the Attribute dataset for every identifier in the Framework dataset.  \"many\" indicates that there may be more than one record in the Attribute dataset for every identifier in the Framework dataset.',	'Character String',	'Must be \"one\" or \"many\"',	''),
(26,	'KeyComplete',	'Identifies that there is at least one record in the Attribute dataset for every record in the Framework dataset.  \"true\" indicates that this is the case. \"false\" indicates that some identifiers in the Framework dataset cannot be found in the Attribute dataset.',	'Boolean',	'Must be \"true\" or \"false\"',	''),
(27,	'Attribute',	'Contains XML elements that describe a data field (i.e column of the dataset).',	'XML elements',	'',	''),
(28,	'type',	'Datatype, as defined by XML schema',	'URI type',	'',	'e.g. \“http://www.w3.org/TR/xmlschema-2/#integer\”'),
(29,	'length',	'Length of the field, in characters or digits',	'Positive Integer',	'',	''),
(30,	'decimals',	'Number of digits after the decimal, for decimal numbers with a fixed number of digits after the decimal.  ',	'Positive Integer',	'',	''),
(31,	'purpose',	'Purpose of the data field, indicating whether the attribute contains data, a linkage key, or other content.',	'Character String',	'',	''),
(32,	'AttributeName',	'The name of the data field.  Generally the name by which the attribute is identified within the RDBMS database.',	'Character String',	'',	''),
(33,	'Values',	'Description of the content of the attribute.',	'XML elements',	'',	''),
(34,	'Rowset',	'Attribute values',	'XML elements',	'',	''),
(35,	'Nominal/Ordinal/Measure/Count',	'Choice of Attribute type.  ',	'XML elements',	'',	''),
(36,	'Nominal',	'Contains XML elements that describe an attribute consisting of Nominal data (i.e. names, such as \"Canada\")',	'XML elements',	'',	''),
(37,	'Ordinal',	'Contains XML elements that describe an attribute consisting of Ordinal data (i.e. rankings, such as \"high=1, medium=2, low=3\"',	'XML elements',	'',	''),
(38,	'Count',	'Contains XML elements that describe an attribute consisting of Count data (i.e. total number of objects, such as \"number of cows\")',	'XML elements',	'',	''),
(39,	'Measure',	'Contains XML elements that describe an attribute consisting of Measure data (i.e. numeric measurement or calculated value such as \"degrees Celsius\")',	'XML elements',	'',	''),
(40,	'Classes',	'Contains XML elements that describe all valid classes for this attribute field.  This element is populated if the field contains classification information of some kind (e.g. geological classifications).',	'XML elements',	'',	''),
(41,	'Exceptions',	'Contains XML elements that describe all valid exception classes for this attribute field.',	'XML elements',	'',	''),
(42,	'Value',	'Contains XML elements that describe a valid (non-null) class that is present in this attribute field.',	'Character String',	'',	''),
(43,	'Identifier',	'Unique identifier within this group of objects.',	'Character String',	'',	''),
(44,	'Null',	'Contains XML elements that describe a valid exception class for this attribute field.',	'XML elements',	'',	''),
(45,	'rank',	'Ordinal ranking for this value',	'Non-negative Integer',	'',	''),
(46,	'UOM',	'Unit of Measure',	'Character String',	'',	''),
(47,	'Uncertainty',	'Contains XML elements that describe the standard measure of uncertainty (u<sub>i</sub>) equal to the positive square root of the estimated variance for this data.  See <a href=\"http://physics.nist.gov/cuu/Uncertainty/\"/>',	'XML elements',	'',	''),
(48,	'reference',	'URL reference to an authoritative description.',	'URI',	'',	''),
(49,	'gaussian',	'Distribution form of the data.  When \"true\" the distribution of the data is Gaussian and Independent and Identically Distributed (IID)',	'Character String',	'\"true\", \"false\", or \"unknown\".  Default is \"unknown\".',	''),
(50,	'Row',	'Contains XML elements that describe a data row which includes selected fields from the database.',	'XML elements',	'',	''),
(51,	'K',	'Key (e.g. polygon identifier) that references the spatial feature to which this row applies. Note that this identifier is a member of the DatasetKey   ',	'Character String',	'',	''),
(52,	'V',	'Value of a specified attribute for the spatial feature identified by the key for this Row.  When this value is null it must be indicated by setting the null attribute to \“true\”.   An identification of the reason may be included in the content of this element, but it must be described in the Exceptions element.  ',	'XML elements',	'',	''),
(53,	'aid',	'Attribute identifier, namely the corresponding AttributeName',	'Character String',	'',	''),
(54,	'null',	'Boolean value, when present and \"true\" indicates that this particular value is missing for some reason, and the contents of the element must be processed accordingly.  ',	'Boolean',	'\"true\", or \"false\".  Default is \"false\".',	'');
UNLOCK TABLES;					
