DROP TABLE IF EXISTS `gschemas`;									
SET @saved_cs_client     = @@character_set_client;									
SET character_set_client = utf8;									
CREATE TABLE `gschemas` (									
  `id` int(11) NOT NULL auto_increment,									
  `Schema` varchar(100) NOT NULL,									
  `XPath` varchar(300) NOT NULL,									
  `Order` int(2) ,									
  `ElementName` varchar(60) ,									
  `Parent` varchar(1) ,									
  `AttributeName` varchar(60) ,									
  `Quantity` varchar(30) ,									
  `Use` varchar(30) ,									
  `DefinitionID` varchar(100),									
  PRIMARY KEY  (`id`)									
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;									
SET character_set_client = @saved_cs_client;									
LOCK TABLES `gschemas` WRITE;									
INSERT INTO `gschemas` (`id`, `Schema`, `XPath`, `Order`, `ElementName`, `Parent`, `AttributeName`, `Quantity`, `Use`, `DefinitionID` ) VALUES 									
(1,	'FrameworkDescriptions',	'',	'0',	'',	'',	'service',	'one',	'mandatory',	'service'),
(2,	'FrameworkDescriptions',	'',	'0',	'',	'',	'version',	'one',	'mandatory',	'version'),
(3,	'FrameworkDescriptions',	'',	'0',	'',	'',	'xml:lang',	'one',	'mandatory',	'xml:lang'),
(4,	'FrameworkDescriptions',	'',	'0',	'',	'',	'xmlns',	'one',	'mandatory',	'xmlns'),
(5,	'FrameworkDescriptions',	'',	'0',	'',	'',	'xmlns:ows',	'one',	'mandatory',	'xmlns:ows'),
(6,	'FrameworkDescriptions',	'',	'0',	'',	'',	'xmlns:xsi',	'one',	'mandatory',	'xmlns:xsi'),
(7,	'FrameworkDescriptions',	'',	'0',	'',	'',	'xsi:schemaLocation',	'one',	'mandatory',	'xsi:schemaLocation'),
(8,	'FrameworkDescriptions',	'',	'1',	'Framework',	'Y',	'',	'one or more',	'mandatory',	'Framework'),
(9,	'FrameworkDescriptions',	'Framework',	'1',	'FrameworkURI',	'N',	'',	'one',	'mandatory',	'FrameworkURI'),
(10,	'FrameworkDescriptions',	'Framework',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(11,	'FrameworkDescriptions',	'Framework',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(12,	'FrameworkDescriptions',	'Framework',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(13,	'FrameworkDescriptions',	'Framework',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(14,	'FrameworkDescriptions',	'Framework',	'6',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(15,	'FrameworkDescriptions',	'Framework',	'7',	'FrameworkKey',	'N',	'',	'one',	'mandatory',	'FrameworkKey'),
(16,	'FrameworkDescriptions',	'Framework',	'8',	'BoundingBox',	'Y',	'',	'one',	'mandatory',	'BoundingBox'),
(17,	'FrameworkDescriptions',	'Framework/BoundingBox',	'1',	'Minimum',	'Y',	'',	'one',	'mandatory',	'Minimum'),
(18,	'FrameworkDescriptions',	'Framework/BoundingBox/Minimum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(19,	'FrameworkDescriptions',	'Framework/BoundingBox/Minimum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(20,	'FrameworkDescriptions',	'Framework/BoundingBox',	'2',	'Maximum',	'Y',	'',	'one',	'mandatory',	'Maximum'),
(21,	'FrameworkDescriptions',	'Framework/BoundingBox/Maximum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(22,	'FrameworkDescriptions',	'Framework/BoundingBox/Maximum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(23,	'DatasetDescriptions',	'',	'0',	'',	'',	'service',	'one',	'mandatory',	'service'),
(24,	'DatasetDescriptions',	'',	'0',	'',	'',	'version',	'one',	'mandatory',	'version'),
(25,	'DatasetDescriptions',	'',	'0',	'',	'',	'xml:lang',	'one',	'mandatory',	'xml:lang'),
(26,	'DatasetDescriptions',	'',	'0',	'',	'',	'xmlns',	'one',	'mandatory',	'xmlns'),
(27,	'DatasetDescriptions',	'',	'0',	'',	'',	'xmlns:ows',	'one',	'mandatory',	'xmlns:ows'),
(28,	'DatasetDescriptions',	'',	'0',	'',	'',	'xmlns:xsi',	'one',	'mandatory',	'xmlns:xsi'),
(29,	'DatasetDescriptions',	'',	'0',	'',	'',	'xsi:schemaLocation',	'one',	'mandatory',	'xsi:schemaLocation'),
(30,	'DatasetDescriptions',	'',	'1',	'Framework',	'Y',	'',	'one',	'mandatory',	'Framework'),
(31,	'DatasetDescriptions',	'Framework',	'1',	'FrameworkURI',	'N',	'',	'one',	'mandatory',	'FrameworkURI'),
(32,	'DatasetDescriptions',	'Framework',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(33,	'DatasetDescriptions',	'Framework',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(34,	'DatasetDescriptions',	'Framework',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(35,	'DatasetDescriptions',	'Framework',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(36,	'DatasetDescriptions',	'Framework',	'6',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(37,	'DatasetDescriptions',	'Framework',	'7',	'FrameworkKey',	'N',	'',	'one',	'mandatory',	'FrameworkKey'),
(38,	'DatasetDescriptions',	'Framework',	'8',	'BoundingBox',	'Y',	'',	'one',	'mandatory',	'BoundingBox'),
(39,	'DatasetDescriptions',	'Framework/BoundingBox',	'1',	'Minimum',	'Y',	'',	'one',	'mandatory',	'Minimum'),
(40,	'DatasetDescriptions',	'Framework/BoundingBox/Minimum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(41,	'DatasetDescriptions',	'Framework/BoundingBox/Minimum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(42,	'DatasetDescriptions',	'Framework/BoundingBox',	'2',	'Maximum',	'Y',	'',	'one',	'mandatory',	'Maximum'),
(43,	'DatasetDescriptions',	'Framework/BoundingBox/Maximum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(44,	'DatasetDescriptions',	'Framework/BoundingBox/Maximum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(45,	'DatasetDescriptions',	'Framework',	'9',	'Dataset',	'Y',	'',	'one or more',	'mandatory',	'Dataset'),
(46,	'DatasetDescriptions',	'Framework/Dataset',	'1',	'DatasetURI',	'N',	'',	'one',	'mandatory',	'DatasetURI'),
(47,	'DatasetDescriptions',	'Framework/Dataset',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(48,	'DatasetDescriptions',	'Framework/Dataset',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(49,	'DatasetDescriptions',	'Framework/Dataset',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(50,	'DatasetDescriptions',	'Framework/Dataset',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(51,	'DatasetDescriptions',	'Framework/Dataset',	'6',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(52,	'DatasetDescriptions',	'Framework/Dataset',	'7',	'DatasetKey',	'Y',	'',	'one',	'mandatory',	'DatasetKey'),
(53,	'DatasetDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(54,	'DatasetDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(55,	'DatasetDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'decimals',	'one',	'mandatory',	'decimals'),
(56,	'DatasetDescriptions',	'Framework/Dataset',	'8',	'KeyRelationship',	'N',	'',	'one',	'mandatory',	'KeyRelationship'),
(57,	'DatasetDescriptions',	'Framework/Dataset',	'9',	'KeyComplete',	'N',	'',	'one',	'mandatory',	'KeyComplete'),
(58,	'DataDescriptions',	'',	'0',	'',	'',	'service',	'one',	'mandatory',	'service'),
(59,	'DataDescriptions',	'',	'0',	'',	'',	'version',	'one',	'mandatory',	'version'),
(60,	'DataDescriptions',	'',	'0',	'',	'',	'xml:lang',	'one',	'mandatory',	'xml:lang'),
(61,	'DataDescriptions',	'',	'0',	'',	'',	'xmlns',	'one',	'mandatory',	'xmlns'),
(62,	'DataDescriptions',	'',	'0',	'',	'',	'xmlns:ows',	'one',	'mandatory',	'xmlns:ows'),
(63,	'DataDescriptions',	'',	'0',	'',	'',	'xmlns:xsi',	'one',	'mandatory',	'xmlns:xsi'),
(64,	'DataDescriptions',	'',	'0',	'',	'',	'xsi:schemaLocation',	'one',	'mandatory',	'xsi:schemaLocation'),
(65,	'DataDescriptions',	'',	'1',	'Framework',	'Y',	'',	'one',	'mandatory',	'Framework'),
(66,	'DataDescriptions',	'Framework',	'1',	'FrameworkURI',	'N',	'',	'one',	'mandatory',	'FrameworkURI'),
(67,	'DataDescriptions',	'Framework',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(68,	'DataDescriptions',	'Framework',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(69,	'DataDescriptions',	'Framework',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(70,	'DataDescriptions',	'Framework',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(71,	'DataDescriptions',	'Framework',	'6',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(72,	'DataDescriptions',	'Framework',	'7',	'FrameworkKey',	'N',	'',	'one',	'mandatory',	'FrameworkKey'),
(73,	'DataDescriptions',	'Framework',	'8',	'BoundingBox',	'Y',	'',	'one',	'mandatory',	'BoundingBox'),
(74,	'DataDescriptions',	'Framework/BoundingBox',	'1',	'Minimum',	'Y',	'',	'one',	'mandatory',	'Minimum'),
(75,	'DataDescriptions',	'Framework/BoundingBox/Minimum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(76,	'DataDescriptions',	'Framework/BoundingBox/Minimum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(77,	'DataDescriptions',	'Framework/BoundingBox',	'2',	'Maximum',	'Y',	'',	'one',	'mandatory',	'Maximum'),
(78,	'DataDescriptions',	'Framework/BoundingBox/Maximum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(79,	'DataDescriptions',	'Framework/BoundingBox/Maximum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(80,	'DataDescriptions',	'Framework',	'9',	'Dataset',	'Y',	'',	'one',	'mandatory',	'Dataset'),
(81,	'DataDescriptions',	'Framework/Dataset',	'1',	'DatasetURI',	'N',	'',	'one',	'mandatory',	'DatasetURI'),
(82,	'DataDescriptions',	'Framework/Dataset',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(83,	'DataDescriptions',	'Framework/Dataset',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(84,	'DataDescriptions',	'Framework/Dataset',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(85,	'DataDescriptions',	'Framework/Dataset',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(86,	'DataDescriptions',	'Framework/Dataset',	'6',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(87,	'DataDescriptions',	'Framework/Dataset',	'7',	'DatasetKey',	'Y',	'',	'one',	'mandatory',	'DatasetKey'),
(88,	'DataDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(89,	'DataDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(90,	'DataDescriptions',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'decimals',	'one',	'mandatory',	'decimals'),
(91,	'DataDescriptions',	'Framework/Dataset',	'8',	'KeyRelationship',	'N',	'',	'one',	'mandatory',	'KeyRelationship'),
(92,	'DataDescriptions',	'Framework/Dataset',	'9',	'KeyComplete',	'N',	'',	'one',	'mandatory',	'KeyComplete'),
(93,	'DataDescriptions',	'Framework/Dataset',	'10',	'Attribute',	'Y',	'',	'one or more',	'mandatory',	'Attribute'),
(94,	'DataDescriptions',	'Framework/Dataset/Attribute',	'0',	'',	'',	'purpose',	'one',	'mandatory',	'purpose'),
(95,	'DataDescriptions',	'Framework/Dataset/Attribute',	'1',	'AttributeName',	'N',	'',	'one',	'mandatory',	'AttributeName'),
(96,	'DataDescriptions',	'Framework/Dataset/Attribute',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(97,	'DataDescriptions',	'Framework/Dataset/Attribute',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(98,	'DataDescriptions',	'Framework/Dataset/Attribute',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(99,	'DataDescriptions',	'Framework/Dataset/Attribute',	'5',	'Values',	'Y',	'',	'one or more',	'mandatory',	'Values'),
(100,	'DataDescriptions',	'Framework/Dataset/Attribute/Values',	'1',	'Nominal|Ordinal|Measure|Count',	'Y',	'',	'one (choice)',	'mandatory',	'Nominal/Ordinal/Measure/Count'),
(101,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(102,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(103,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(104,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal',	'1',	'Classes',	'Y',	'',	'one',	'mandatory',	'Classes'),
(105,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'1',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(106,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'2',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(107,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'3',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(108,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'4',	'Value',	'Y',	'',	'one or more',	'mandatory',	'Value'),
(109,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'0',	'',	'',	'rank',	'one',	'mandatory',	'rank'),
(110,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(111,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(112,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(113,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(114,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(115,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'decimals',	'one',	'mandatory',	'decimals'),
(116,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'length',	'zero or one',	'optional',	'length'),
(117,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal',	'1',	'Classes',	'Y',	'',	'one',	'mandatory',	'Classes'),
(118,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'1',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(119,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'2',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(120,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'3',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(121,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'4',	'Value',	'Y',	'',	'one or more',	'mandatory',	'Value'),
(122,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'0',	'',	'',	'rank',	'one',	'mandatory',	'rank'),
(123,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(124,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(125,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(126,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(127,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(128,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(129,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(130,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'1',	'UOM',	'N',	'',	'one',	'mandatory',	'UOM'),
(131,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/UOM',	'0',	'',	'',	'reference',	'one',	'mandatory',	'reference'),
(132,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'',	'Uncertainty',	'N',	'',	'zero or one',	'optional',	'Uncertainty'),
(133,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Uncertainty',	'0',	'',	'',	'gaussian',	'zero or one',	'optional',	'gaussian'),
(134,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(135,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(136,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(137,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'1',	'UOM',	'Y',	'',	'one',	'mandatory',	'UOM'),
(138,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/UOM',	'0',	'',	'',	'reference',	'one',	'mandatory',	'reference'),
(139,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'',	'Uncertainty',	'N',	'',	'zero or one',	'optional',	'Uncertainty'),
(140,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Uncertainty',	'0',	'',	'',	'gaussian',	'zero or one',	'optional',	'gaussian'),
(141,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(142,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(143,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(144,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(145,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(146,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(147,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(148,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(149,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(150,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(151,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(152,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(153,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(154,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(155,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(156,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(157,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(158,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(159,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(160,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(161,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(162,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(163,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(164,	'DataDescriptions',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(165,	'GDAS',	'',	'0',	'',	'',	'service',	'one',	'mandatory',	'service'),
(166,	'GDAS',	'',	'0',	'',	'',	'version',	'one',	'mandatory',	'version'),
(167,	'GDAS',	'',	'0',	'',	'',	'xml:lang',	'one',	'mandatory',	'xml:lang'),
(168,	'GDAS',	'',	'0',	'',	'',	'xmlns',	'one',	'mandatory',	'xmlns'),
(169,	'GDAS',	'',	'0',	'',	'',	'xmlns:ows',	'one',	'mandatory',	'xmlns:ows'),
(170,	'GDAS',	'',	'0',	'',	'',	'xmlns:xsi',	'one',	'mandatory',	'xmlns:xsi'),
(171,	'GDAS',	'',	'0',	'',	'',	'xsi:schemaLocation',	'one',	'mandatory',	'xsi:schemaLocation'),
(172,	'GDAS',	'',	'1',	'Framework',	'Y',	'',	'one',	'mandatory',	'Framework'),
(173,	'GDAS',	'Framework',	'1',	'FrameworkURI',	'N',	'',	'one',	'mandatory',	'FrameworkURI'),
(174,	'GDAS',	'Framework',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(175,	'GDAS',	'Framework',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(176,	'GDAS',	'Framework',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(177,	'GDAS',	'Framework',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(178,	'GDAS',	'Framework',	'6',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(179,	'GDAS',	'Framework',	'7',	'FrameworkKey',	'N',	'',	'one',	'mandatory',	'FrameworkKey'),
(180,	'GDAS',	'Framework',	'8',	'BoundingBox',	'Y',	'',	'one',	'mandatory',	'BoundingBox'),
(181,	'GDAS',	'Framework/BoundingBox',	'1',	'Minimum',	'Y',	'',	'one',	'mandatory',	'Minimum'),
(182,	'GDAS',	'Framework/BoundingBox/Minimum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(183,	'GDAS',	'Framework/BoundingBox/Minimum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(184,	'GDAS',	'Framework/BoundingBox',	'2',	'Maximum',	'Y',	'',	'one',	'mandatory',	'Maximum'),
(185,	'GDAS',	'Framework/BoundingBox/Maximum',	'1',	'Latitude',	'N',	'',	'one',	'mandatory',	'Latitude'),
(186,	'GDAS',	'Framework/BoundingBox/Maximum',	'2',	'Longitude',	'N',	'',	'one',	'mandatory',	'Longitude'),
(187,	'GDAS',	'Framework',	'9',	'Dataset',	'Y',	'',	'one',	'mandatory',	'Dataset'),
(188,	'GDAS',	'Framework/Dataset',	'1',	'DatasetURI',	'N',	'',	'one',	'mandatory',	'DatasetURI'),
(189,	'GDAS',	'Framework/Dataset',	'2',	'Organization',	'N',	'',	'one',	'mandatory',	'Organization'),
(190,	'GDAS',	'Framework/Dataset',	'3',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(191,	'GDAS',	'Framework/Dataset',	'4',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(192,	'GDAS',	'Framework/Dataset',	'5',	'ReleaseDate',	'N',	'',	'one',	'mandatory',	'ReleaseDate'),
(193,	'GDAS',	'Framework/Dataset',	'6',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(194,	'GDAS',	'Framework/Dataset',	'7',	'DatasetKey',	'Y',	'',	'one',	'mandatory',	'DatasetKey'),
(195,	'GDAS',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(196,	'GDAS',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(197,	'GDAS',	'Framework/Dataset/DatasetKey',	'0',	'',	'',	'decimals',	'one',	'mandatory',	'decimals'),
(198,	'GDAS',	'Framework/Dataset',	'8',	'KeyRelationship',	'N',	'',	'one',	'mandatory',	'KeyRelationship'),
(199,	'GDAS',	'Framework/Dataset',	'9',	'KeyComplete',	'N',	'',	'one',	'mandatory',	'KeyComplete'),
(200,	'GDAS',	'Framework/Dataset',	'10',	'Attribute',	'Y',	'',	'one or more',	'mandatory',	'Attribute'),
(201,	'GDAS',	'Framework/Dataset/Attribute',	'0',	'',	'',	'purpose',	'one',	'mandatory',	'purpose'),
(202,	'GDAS',	'Framework/Dataset/Attribute',	'1',	'AttributeName',	'N',	'',	'one',	'mandatory',	'AttributeName'),
(203,	'GDAS',	'Framework/Dataset/Attribute',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(204,	'GDAS',	'Framework/Dataset/Attribute',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(205,	'GDAS',	'Framework/Dataset/Attribute',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(206,	'GDAS',	'Framework/Dataset/Attribute',	'5',	'Values',	'Y',	'',	'one or more',	'mandatory',	'Values'),
(207,	'GDAS',	'Framework/Dataset/Attribute/Values',	'1',	'Nominal|Ordinal|Measure|Count',	'Y',	'',	'one (choice)',	'mandatory',	'Nominal/Ordinal/Measure/Count'),
(208,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(209,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(210,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(211,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal',	'1',	'Classes',	'Y',	'',	'one',	'mandatory',	'Classes'),
(212,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'1',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(213,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'2',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(214,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'3',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(215,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes',	'4',	'Value',	'Y',	'',	'one or more',	'mandatory',	'Value'),
(216,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'0',	'',	'',	'rank',	'one',	'mandatory',	'rank'),
(217,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(218,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(219,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(220,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Classes/Value',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(221,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(222,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'decimals',	'one',	'mandatory',	'decimals'),
(223,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal',	'0',	'',	'',	'length',	'zero or one',	'optional',	'length'),
(224,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal',	'1',	'Classes',	'Y',	'',	'one',	'mandatory',	'Classes'),
(225,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'1',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(226,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'2',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(227,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'3',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(228,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes',	'4',	'Value',	'Y',	'',	'one or more',	'mandatory',	'Value'),
(229,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'0',	'',	'',	'rank',	'one',	'mandatory',	'rank'),
(230,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(231,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(232,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(233,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Classes/Value',	'4',	'Documentation',	'N',	'',	'one',	'mandatory',	'Documentation'),
(234,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(235,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(236,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(237,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'1',	'UOM',	'N',	'',	'one',	'mandatory',	'UOM'),
(238,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/UOM',	'0',	'',	'',	'reference',	'one',	'mandatory',	'reference'),
(239,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'',	'Uncertainty',	'N',	'',	'zero or one',	'optional',	'Uncertainty'),
(240,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Uncertainty',	'0',	'',	'',	'gaussian',	'zero or one',	'optional',	'gaussian'),
(241,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'type',	'one',	'mandatory',	'type'),
(242,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'length',	'one',	'mandatory',	'length'),
(243,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'0',	'',	'',	'decimals',	'zero or one',	'optional',	'decimals'),
(244,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'1',	'UOM',	'Y',	'',	'one',	'mandatory',	'UOM'),
(245,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/UOM',	'0',	'',	'',	'reference',	'one',	'mandatory',	'reference'),
(246,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'',	'Uncertainty',	'N',	'',	'zero or one',	'optional',	'Uncertainty'),
(247,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Uncertainty',	'0',	'',	'',	'gaussian',	'zero or one',	'optional',	'gaussian'),
(248,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(249,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(250,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(251,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(252,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(253,	'GDAS',	'Framework/Dataset/Attribute/Values/Nominal/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(254,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(255,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(256,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(257,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(258,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(259,	'GDAS',	'Framework/Dataset/Attribute/Values/Ordinal/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(260,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(261,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(262,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(263,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(264,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(265,	'GDAS',	'Framework/Dataset/Attribute/Values/Measure/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(266,	'GDAS',	'Framework/Dataset/Attribute/Values/Count',	'1',	'Exceptions',	'Y',	'',	'zero or one',	'optional',	'Exceptions'),
(267,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Exceptions',	'1',	'Null',	'Y',	'',	'one',	'mandatory',	'Null'),
(268,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'1',	'Identifier',	'N',	'',	'one',	'mandatory',	'Identifier'),
(269,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'2',	'Title',	'N',	'',	'one',	'mandatory',	'Title'),
(270,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'3',	'Abstract',	'N',	'',	'one',	'mandatory',	'Abstract'),
(271,	'GDAS',	'Framework/Dataset/Attribute/Values/Count/Exceptions/Null',	'4',	'Documentation',	'N',	'',	'zero or one',	'optional',	'Documentation'),
(272,	'GDAS',	'Framework/Dataset',	'11',	'Rowset',	'Y',	'',	'one',	'mandatory',	'Rowset'),
(273,	'GDAS',	'Framework/Dataset/Rowset',	'1',	'Row',	'Y',	'',	'one or more',	'mandatory',	'Row'),
(274,	'GDAS',	'Framework/Dataset/Rowset/Row',	'1',	'K',	'N',	'',	'one',	'mandatory',	'K'),
(275,	'GDAS',	'Framework/Dataset/Rowset/Row',	'2',	'V',	'N',	'',	'one or more',	'mandatory',	'V'),
(276,	'GDAS',	'Framework/Dataset/Rowset/Row/V',	'0',	'',	'',	'aid',	'zero or one',	'optional',	'aid'),
(277,	'GDAS',	'Framework/Dataset/Rowset/Row/V',	'0',	'',	'',	'null',	'zero or one',	'optional',	'null');
UNLOCK TABLES;									
