#!/bin/bash
MAPSERV="/usr/lib/cgi-bin/mapserv"
MAPFILE="/usr/local/httpd/lsrs/public/batch/results/20110421t210009r8704/mapfile.map"
if [ "${REQUEST_METHOD}" != "GET" ]; then
  echo "Content-type: text/html"
  echo ""
  echo ""
  echo "Sorry, I only understand GET requests."
  exit
fi
if [ -z ${QUERY_STRING} ] ; then
  QUERY_STRING="map=${MAPFILE}"
else
  QUERY_STRING="map=${MAPFILE}&${QUERY_STRING}"
fi
exec ${MAPSERV}
exit
