class KmlController < ApplicationController

  def create
		resultsDir = "#{Rails.root.to_s}/public/batch/results/#{params[:tmpdir]}"
		@controlHash = YAML.load_file("#{resultsDir}/control.yml")
		
    # load ratings from GDAS XML file
    require "#{Rails.root.to_s}/app/helpers/libxml-helper"
    @gdas = File.open("#{resultsDir}/output.xml").read().to_libxml_doc.root
    @gdas.register_default_namespace("tjs")
    rowsXmlArray = @gdas.search("//tjs:GDAS/tjs:Framework/tjs:Dataset/tjs:Rowset/tjs:Row")
		
    # create hash containing the data to be joined
    @keyvalues = Hash.new
    rowsXmlArray.each do |i|
      i.register_default_namespace("tjs")
      @keyvalues[i.search("tjs:K").to_a.first.content]=i.search("tjs:V").to_a.first.content
    end  
		
    # create mapserver template file for WMS GetFeatureInfo requests
		#File.delete("#{resultsDir}/output.kml") this doesn't work apparently
    kml = File.open("#{resultsDir}/output.kml","w")
    kml.puts '<?xml version="1.0" encoding="UTF-8" standalone="no"?>'
    kml.puts '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd">'
    kml.puts '<Document id="LSRS rating">'
		kml.puts '  <name>'+@controlHash["FrameworkName"]+' '+@controlHash["Crop"]+'</name>'
		kml.puts '  <Snippet></Snippet>'
		kml.puts '  <Folder id="legend">'
		kml.puts '  	<name>Legend</name>'
		kml.puts '  	<Style id="LegendRadioFolder2"><IconStyle><scale>0</scale></IconStyle><ListStyle><listItemType>radioFolder</listItemType></ListStyle></Style>'
		kml.puts ''
		kml.puts '  	<ScreenOverlay id="A2"><name>Upper Left</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.01" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.01" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="B2"><name>Upper Center</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.5" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.5" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="C2"><name>Upper Right</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.99" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.99" y="0.99" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="D2"><name>Center Left</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.01" y="0.5" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.01" y="0.5" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="E2"><name>Center</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="F2"><name>Center Right</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.99" y="0.5" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.99" y="0.5" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="G2"><name>Lower Left</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.01" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.01" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="H2"><name>Lower Center</name>'
		kml.puts '  	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.5" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.5" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<ScreenOverlay id="I2"><name>Lower Right</name>'
		kml.puts ' 	  <color>b0ffffff</color>'
		kml.puts '  		<Icon><href>http://lsrs.gis.agr.gc.ca/images//legend2.png</href></Icon>'
		kml.puts '  		<overlayXY x="0.99" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  		<screenXY x="0.99" y="0.01" xunits="fraction" yunits="fraction"/>'
		kml.puts '  	</ScreenOverlay>'
		kml.puts '  	<Placemark id="ID_2"><name>None</name>'
		kml.puts '  	 <styleUrl>#LegendRadioFolder2</styleUrl>'
		kml.puts '  	</Placemark>'
		kml.puts '  </Folder>'
		kml.puts '  <Folder id="FeatureLayer5">'
		kml.puts '    <name>'+params[:tmpdir]+'</name>'
		kml.puts '    <Snippet></Snippet>'
		for poly in @keyvalues do
			coordinatesArray = File.open("/production/geodata/#{@controlHash["FrameworkName"].split("_").join("/")}/kml/#{poly[0]}","r").readlines
			for @polygon in coordinatesArray do
				kml.puts '    <Placemark id="'+poly[0]+'">'
				kml.puts '      <name>'+poly[0]+'</name>'
				kml.puts '      <Snippet></Snippet>'
				kml.puts '      <description><![CDATA['
				kml.puts '<p>LSRS rating: '+poly[1]+'</p>'
				kml.puts '<p><a href="http://lsrs.gis.agr.gc.ca/batch/results/'+params[:tmpdir]+'/details/'+poly[0]+'.xml">details</a></p>'
				kml.puts ']]></description>'
				kml.puts '      <styleUrl>#class'+poly[1][0]+'</styleUrl>'
				kml.puts @polygon
				kml.puts '    </Placemark>'
			end #for @polygon
		end # for poly
		kml.puts '  </Folder>'
		kml.puts ''
		kml.puts '  <Style id="class1">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf08b246</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class2">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf57df9d</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class3">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf92d8bf</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class4">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf83fbfb</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class5">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf51cff9</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class6">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf557fab</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="class7">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf5252e1</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '  <Style id="classN">'
		kml.puts '    <LabelStyle>'
		kml.puts '      <color>00000000</color>'
		kml.puts '      <scale>0.000000</scale>'
		kml.puts '    </LabelStyle>'
		kml.puts '    <LineStyle>'
		kml.puts '      <color>66000000</color>'
		kml.puts '      <width>0.400000</width>'
		kml.puts '    </LineStyle>'
		kml.puts '    <PolyStyle>'
		kml.puts '      <color>bf6e6e6e</color>'
		kml.puts '      <outline>1</outline>'
		kml.puts '    </PolyStyle>'
		kml.puts '  </Style>'
		kml.puts '</Document>'
		kml.puts '</kml>'
    kml.close
		Dir.chdir(resultsDir) 
		`zip output.kmz output.kml`
		`rm output.kml`
		
		
    # render output and close
    #render :file => (resultsDir + "/output.kmz"), :content_type => "application/zip", :layout => false and return and exit 1
		send_file  (resultsDir + "/output.kmz"), :type => 'application/vnd.google-earth.kmz', :disposition => 'inline'

  end
  

end
